[package]
name = "halo2-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "factorisation"
path = "src/factorisation.rs"

[dependencies]
halo2_proofs = "0.2.0"
